[project]
name = "hasura-graphql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standart]>=0.115.7",
    "orjson>=3.10.15",
    "tortoise-orm[asyncmy]>=0.24.0",
    "uvicorn>=0.34.0",
]
